"""worktrees-hives: Python orchestrator for issue-to-PR and PR-babysit workflows.

Orchestration policy only. Worktrees, path sandbox, branch checks, and safe
``git``/``gh`` execution belong to the Rust ``wh`` binary — use :class:`WhClient`.
"""

__version__ = "0.2.0"

from worktrees_hives.aggregate import (
    AGGREGATE_SCHEMA_VERSION,
    NEVER_MERGE_LINE,
    REQUIRED_AGGREGATE_MD_SECTIONS,
    AggregateReport,
    AggregateUnit,
    UnitOutcome,
    collect_unit,
    parse_aggregate_json,
    validate_aggregate_markdown,
    write_aggregate_pair,
)
from worktrees_hives.attribution import (
    AttributionConfig,
    AttributionPlacement,
    ReplyTemplate,
    format_attribution,
    format_reply,
)
from worktrees_hives.babysit import (
    BabysitCycle,
    BabysitResult,
    CheckRun,
    PRState,
    ReviewThread,
    ThreadAction,
    babysit_multiple,
    classify_pr,
)
from worktrees_hives.bridge import WhClient
from worktrees_hives.ci_taxonomy import (
    CheckClass,
    CheckConclusion,
    CheckEntry,
    ClassificationReport,
    ClassifiedCheck,
    Policy,
    classify_check,
    classify_checks,
    parse_check_entry,
    rerun_command,
    should_rerun,
)
from worktrees_hives.claim import (
    ClaimError,
    ClaimExistsError,
    ClaimManager,
    ClaimResult,
    IsolationError,
)
from worktrees_hives.contract import ErrorResponse, Response, SuccessResponse
from worktrees_hives.errors import (
    AggregateValidationError,
    FindingsValidationError,
    PolicyError,
    ResearchValidationError,
    WhBinaryNotFoundError,
    WhError,
    WhJsonDecodeError,
    WhProcessError,
    WhSchemaError,
)
from worktrees_hives.findings import (
    FINDINGS_SCHEMA_VERSION,
    REQUIRED_MD_SECTIONS,
    AgentRole,
    Finding,
    FindingsReport,
    FindingType,
    ReportStatus,
    empty_findings_markdown_template,
    load_findings_pair,
    parse_findings_json,
    validate_findings_markdown,
    write_findings_pair,
)
from worktrees_hives.issue_to_pr import (
    IssueToPr,
    IssueToPrConfig,
    IssueToPrError,
    IssueToPrResult,
)
from worktrees_hives.lab_jobs import (
    LAB_JOBS_SCHEMA_VERSION,
    LabJob,
    LabJobError,
    LabJobExistsError,
    LabJobManager,
    LabJobNotFoundError,
    LabJobStatus,
    LabJobStore,
    default_lab_jobs_path,
)
from worktrees_hives.lab_run import (
    FINDINGS_JSON_NAME,
    FINDINGS_MD_NAME,
    LabRunError,
    LabRunResult,
    assert_command_allowed,
    findings_paths,
    run_lab_unit,
)
from worktrees_hives.orchestrator import (
    Orchestrator,
    OrchestratorReport,
    WorkerResult,
    WorkerSpec,
    WorkerStatus,
)
from worktrees_hives.research import (
    RESEARCH_CONTRACT_SCHEMA_VERSION,
    ResearchContract,
    ResearchOutcome,
    parse_research_json,
)
from worktrees_hives.stacks import (
    DEFAULT_ALLOWED_OWNERS,
    PRInfo,
    Stack,
    StackDetector,
    StackMember,
    StackType,
    find_standalone_prs,
    load_allowed_owners_from_env,
    order_prs_bottom_up,
    resolve_allowed_owners,
)
from worktrees_hives.stacks import PRState as StackPRState

__all__ = [
    "AGGREGATE_SCHEMA_VERSION",
    "DEFAULT_ALLOWED_OWNERS",
    "FINDINGS_JSON_NAME",
    "FINDINGS_MD_NAME",
    "FINDINGS_SCHEMA_VERSION",
    "LAB_JOBS_SCHEMA_VERSION",
    "NEVER_MERGE_LINE",
    "REQUIRED_AGGREGATE_MD_SECTIONS",
    "REQUIRED_MD_SECTIONS",
    "RESEARCH_CONTRACT_SCHEMA_VERSION",
    "AgentRole",
    "AggregateReport",
    "AggregateUnit",
    "AggregateValidationError",
    "AttributionConfig",
    "AttributionPlacement",
    "BabysitCycle",
    "BabysitResult",
    "CheckClass",
    "CheckConclusion",
    "CheckEntry",
    "CheckRun",
    "ClaimError",
    "ClaimExistsError",
    "ClaimManager",
    "ClaimResult",
    "ClassificationReport",
    "ClassifiedCheck",
    "ErrorResponse",
    "Finding",
    "FindingType",
    "FindingsReport",
    "FindingsValidationError",
    "IsolationError",
    "IssueToPr",
    "IssueToPrConfig",
    "IssueToPrError",
    "IssueToPrResult",
    "LabJob",
    "LabJobError",
    "LabJobExistsError",
    "LabJobManager",
    "LabJobNotFoundError",
    "LabJobStatus",
    "LabJobStore",
    "LabRunError",
    "LabRunResult",
    "Orchestrator",
    "OrchestratorReport",
    "PRInfo",
    "PRState",
    "Policy",
    "PolicyError",
    "ReplyTemplate",
    "ReportStatus",
    "ResearchContract",
    "ResearchOutcome",
    "ResearchValidationError",
    "Response",
    "ReviewThread",
    "Stack",
    "StackDetector",
    "StackMember",
    "StackPRState",
    "StackType",
    "SuccessResponse",
    "ThreadAction",
    "UnitOutcome",
    "WhBinaryNotFoundError",
    "WhClient",
    "WhError",
    "WhJsonDecodeError",
    "WhProcessError",
    "WhSchemaError",
    "WorkerResult",
    "WorkerSpec",
    "WorkerStatus",
    "__version__",
    "assert_command_allowed",
    "babysit_multiple",
    "classify_check",
    "classify_checks",
    "classify_pr",
    "collect_unit",
    "default_lab_jobs_path",
    "empty_findings_markdown_template",
    "find_standalone_prs",
    "findings_paths",
    "format_attribution",
    "format_reply",
    "load_allowed_owners_from_env",
    "load_findings_pair",
    "order_prs_bottom_up",
    "parse_aggregate_json",
    "parse_check_entry",
    "parse_findings_json",
    "parse_research_json",
    "rerun_command",
    "resolve_allowed_owners",
    "run_lab_unit",
    "should_rerun",
    "validate_aggregate_markdown",
    "validate_findings_markdown",
    "write_aggregate_pair",
    "write_findings_pair",
]
